version: '3.9'
#################### NETWORKS ####################
networks:
  frontend_net:
    name: "frontend_net"
  backend_net:
    name: " backend_net"
  ai_net:
    name: "ai_net"

#################### SERVICES ####################
services:
#################### BACKEND ####################
  backend_app:
    container_name: nodeJsApp
    build:
      context: .
      dockerfile: ./App_Backend/DockerFile
    env_file: .env
    ports:
      - "8082:8082"
    environment:
      - NODE_ENV=production
    networks:
      - backend_net
      - frontend_net
      - ai_net
    volumes:
       - ./App_Backend/uploads/images_users:/app/uploads/images_users
    restart: unless-stopped

#################### FRONTEND ####################
  frontent_app:
    container_name: reactJsApp
    build:
      context: .
      dockerfile: ./App_Web/DockerFile
    ports:
      - "8083:80"
    networks:
      - frontend_net
      - backend_net
    depends_on:
      - backend_app
    restart: unless-stopped

#################### AI MODEL ####################
  python_script:
    build:
      context: ./AI_Model
    command: python /app/scripts/update_all_users_reco.py
    networks:
      - ai_net