FROM node:latest AS build
WORKDIR /build

COPY App_Web/alchemix_app/package.json package.json
COPY App_Web/alchemix_app/package-lock.json package-lock.json
RUN npm install
RUN npm ci

COPY App_Web/alchemix_app/public public
COPY App_Web/alchemix_app/src/ src
RUN npm run build

FROM nginx:alpine
COPY --from=build /build/build/ /usr/share/nginx/html
