FROM node:latest AS build
WORKDIR /build

COPY App_Web/alchemix_app/package.json package.json
COPY App_Web/alchemix_app/package-lock.json package-lock.json
RUN npm install
RUN npm ci

COPY App_Web/alchemix_app/public public
COPY App_Web/alchemix_app/src/ src
RUN npm run build

FROM nginx:alpine
# Nginx configuration
COPY App_Web/nginx.conf /etc/nginx/nginx.conf
COPY --from=build /build/build/ /usr/share/nginx/html
EXPOSE 8083
CMD ["nginx", "-g", "daemon off;"]